name: Build Maps Notification Reader

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Get date for cache key
      - name: Get Date
        id: get-date
        run: |
          echo "date=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_OUTPUT
        shell: bash

      # Cache global Buildozer dir
      - name: Cache Buildozer global directory
        uses: actions/cache@v4
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}-${{ steps.get-date.outputs.date }}
          restore-keys: |
            buildozer-global-${{ hashFiles('buildozer.spec') }}-
            buildozer-global-

      # Cache local Buildozer dir
      - name: Cache Buildozer local directory
        uses: actions/cache@v4
        with:
          path: .buildozer
          key: buildozer-local-${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}-v2
          restore-keys: |
            buildozer-local-${{ runner.os }}-${{ steps.get-date.outputs.date }}-
            buildozer-local-${{ runner.os }}-

      # Clean old build dirs (safe)
      - name: Clean build directories
        run: |
          echo "Cleaning build directories..."
          [ -d ".buildozer/android/platform/build" ] && rm -rf .buildozer/android/platform/build
          [ -d ".buildozer/android/app" ] && rm -rf .buildozer/android/app
          [ -d "bin" ] && rm -rf bin
          ls -la .buildozer/ || echo "No .buildozer directory yet"

      # Build APK
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android release
          buildozer_version: stable

      # Upload APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: maps-notification-reader-apk
          path: ${{ steps.buildozer.outputs.filename }}
          retention-days: 30

      
